default: &default
#  adapter: sqlite3
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000
  adapter: mysql2
  username: root
  # password:
  # socket: /tmp/mysql.sock
  encoding: utf8
  pool: 6
  host: 127.0.0.1

development:
  <<: *default
#  database: db/development.sqlite3
  database: fremaket_development

test:
  <<: *default
#  database: db/test.sqlite3
  database: fremaket_test

production:
  <<: *default
#  database: db/production.sqlite3
  database: fremaket_production
  username: root
  # password:
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # socket: /tmp/mysql.sock
  # socket: /var/lib/mysql/mysql.sock